spring:
  profiles:
    active: local
  session:
    store-type: REDIS
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mariadb://localhost:3306/podong?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: podong
    password: 1234
mybatis:
  config-location: classpath*:mybatis-config.xml
  data:
    mongodb:
      host: localhost
      port: 27017
      database: armsdb